name: DEPLOYDEV

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to dev
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: echo Deploy t dev after merge to master!
    - name:
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
