name: DEPLOYDEV

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: fjogeleit/http-request-action@master
        with:
          url: https://dev.b2brouter.net
          method: 'GET'
